# soil-3_3cm data from New-Minidisk-Infiltrometer-Macro  example ----------
# data from soil-b are random numbers

data_example <- tribble(
  ~ "time",
  ~ "volume",
  ~ "soilID",
  0,
  95,
  "soil-a_3cm_water",
  30,
  89,
  "soil-a_3cm_water",
  60,
  86,
  "soil-a_3cm_water",
  90,
  83,
  "soil-a_3cm_water",
  120,
  80,
  "soil-a_3cm_water",
  150,
  77,
  "soil-a_3cm_water",
  180,
  75,
  "soil-a_3cm_water",
  210,
  73,
  "soil-a_3cm_water",
  240,
  71,
  "soil-a_3cm_water",
  270,
  69,
  "soil-a_3cm_water",
  300,
  67,
  "soil-a_3cm_water",
  0,
  80,
  "soil-b_3cm_water",
  20,
  75,
  "soil-b_3cm_water",
  40,
  66,
  "soil-b_3cm_water",
  55,
  59,
  "soil-b_3cm_water",
  70,
  44,
  "soil-b_3cm_water",
  0,
  88,
  "soil-b_3cm_alcohol",
  20,
  85,
  "soil-b_3cm_alcohol",
  35,
  80,
  "soil-b_3cm_alcohol",
  70,
  55,
  "soil-b_3cm_alcohol",
  100,
  35,
  "soil-b_3cm_alcohol",
  0,
  91,
  "soil-b_6cm_water",
  25,
  83,
  "soil-b_6cm_water",
  55,
  80,
  "soil-b_6cm_water",
  80,
  78,
  "soil-b_6cm_water",
  120,
  61,
  "soil-b_6cm_water",
  150,
  57,
  "soil-b_6cm_water",
  200,
  49,
  "soil-b_6cm_water"
)

# soil-3_3cm data from New-Minidisk-Infiltrometer-Macro  example ----------
# data from soil-b is a random texture

soil_data_example <- tribble(~ "soilID",
                             ~ "texture",
                             "soil-a_3cm_water",
                             "loamy sand",
                             "soil-b_3cm_water",
                             "sandy loam",
                             "soil-b_3cm_alcohol",
                             "sandy loam",
                             "soil-b_6cm_water",
                             "sandy loam")
